# -*- coding: utf-8 -*-
"""nlp_tokenazationipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17v-F1kwf-jc-hAYJiLnC7MfCilyxvSex
"""

import pandas as pd

df=pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv')

df

df.info()

df.isnull().sum()

df.dropna()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

df.head()

df.shape

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    if pd.isnull(text):
        return ""

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]

    return " ".join(tokens)

df['clean_review'] = df['Review Text'].apply(clean_text)

from collections import Counter

positive_reviews = df[df['Rating'] >= 4]['clean_review']
all_words = " ".join(positive_reviews).split()

Counter(all_words).most_common(20)

negative_reviews = df[df['Rating'] <= 2]['clean_review']
all_words_neg = " ".join(negative_reviews).split()

Counter(all_words_neg).most_common(20)

def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

df['Sentiment'] = df['Rating'].apply(label_sentiment)

df = df[df['Sentiment'] != "Neutral"]

from sklearn.model_selection import train_test_split

X = df['clean_review']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)

y_pred_lr = lr.predict(X_test_tfidf)
print(classification_report(y_test, y_pred_lr))

from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

y_pred_nb = nb.predict(X_test_tfidf)
print(classification_report(y_test, y_pred_nb))

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")

sample_reviews = df['Review Text'].head(100).tolist()

predictions = sentiment_model(sample_reviews)
predictions[:5]

def convert_label(label):
    return "Positive" if label == "POSITIVE" else "Negative"

hf_preds = [convert_label(p['label']) for p in predictions]

from sklearn.metrics import accuracy_score

actual = df['Sentiment'].head(100)
accuracy_score(actual, hf_preds)

